name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          cd app
          npm install

      - name: Rodar aplicação (PM2)
        run: |
          cd app
          pm2 start app.js --name hw-devops-test || pm2 restart hw-devops-test
